-- 카드 정보 테이블 생성 (UUID 기반, created_at 제거)
CREATE TABLE IF NOT EXISTS card_info
(
    card_id        BINARY(16)   NOT NULL,
    card_name      VARCHAR(200) NOT NULL,
    company        VARCHAR(120) NOT NULL,
    benefits       TEXT         NOT NULL,
    spend_required VARCHAR(100),
    brand          VARCHAR(100),
    profile        VARCHAR(40),
    PRIMARY KEY (card_id)
);

INSERT INTO card_info (card_id, card_name, company, benefits, spend_required, brand, profile)
VALUES (UUID_TO_BIN(UUID()), 'ONE 체크카드', '케이뱅크', '무제한 캐시백 최대 1.1%, 자주 쓰는 곳 5% 캐시백, 3번 결제마다 1,000원 캐시백', '없음', 'VISA',
        NULL),
       (UUID_TO_BIN(UUID()), '노리2 체크카드 (KB Pay)', 'KB국민카드',
        '최대 30,000원 캐시백, 커피·모바일·문화 10% 할인, 뷰티·편의점 5% 할인, KB Pay 2% 추가할인', '20만원 이상', 'VISA, Master', NULL),
       (UUID_TO_BIN(UUID()), '네이버페이 머니카드', '네이버페이', '해외 온라인·오프라인 결제 3% 포인트, 네이버쇼핑 1.5% 포인트, 국내 일반 0.3% 포인트', '없음',
        'VISA', NULL),
       (UUID_TO_BIN(UUID()), 'KB 틴업 체크카드', 'KB국민카드', '편의점 5% 할인, 다이소·올리브영 5% 할인, PC방·모바일 5% 할인, 월 최대 3만 포인트', '없음',
        'Master', NULL),
       (UUID_TO_BIN(UUID()), '더나은 체크카드', 'MG 새마을금고', '모바일 결제·온라인 쇼핑·커피 20% 할인', '30만원 이상', 'VISA', NULL),
       (UUID_TO_BIN(UUID()), '트래블러스 체크카드', 'KB국민카드', '해외이용수수료 면제, 철도·현지식당 5,000원 할인, 연간 최대 3만포인트', '20만원 이상', 'Master',
        NULL),
       (UUID_TO_BIN(UUID()), '토스뱅크 체크카드', '토스뱅크',
        '일상 7대 업종 월 최대 35,000원 캐시백, 온라인 결제 7대 업종 월 최대 14,000원 캐시백, 국내 어디서나 0.3% 캐시백', '없음', 'Master', NULL),
       (UUID_TO_BIN(UUID()), '네이버페이 머니 하나 체크카드', '하나카드', '네이버페이 포인트 1.2% 적립', '25만원 이상', 'Master', NULL),
       (UUID_TO_BIN(UUID()), '신한카드 SOL 트래블 체크', '신한카드', '해외이용수수료 면제, 공항라운지 무료, 해외 대중교통 1% 할인', '없음', 'Master', NULL),
       (UUID_TO_BIN(UUID()), '카카오페이 신한 체크카드', '신한카드', '카카오페이 2% 적립, 대중교통 3% 적립, CGV 최대 3,000원 적립', '없음', 'Master',
        NULL),
       (UUID_TO_BIN(UUID()), '신한카드 Deep Dream 체크', '신한카드',
        '기본 0.2% 적립, 드림적립 0.6% (할인점·편의점·카페 등), 챙겨드림 1.0% (가장 많이 쓴 영역)', '없음', 'VISA, UnionPay', NULL),
       (UUID_TO_BIN(UUID()), '개이득 체크카드', '우체국(우정사업본부)', '국내 가맹점 0.3% 캐시백, OTT 30% 캐시백, 패션 온라인 30% 캐시백', '없음', 'VISA',
        NULL),
       (UUID_TO_BIN(UUID()), '모빌리언스카드', 'KG 모빌리언스', '온라인 1% 적립, 오프라인 0.5% 적립, 편의점/카페/생활 6~8% 적립, KFC 10% 할인', '없음',
        '미확인', NULL),
       (UUID_TO_BIN(UUID()), '노리2 체크카드 (Global)', 'KB국민카드', '커피·모바일·문화 10% 할인, 해외이용 2% 할인, 공항라운지 연 1회', '20만원 이상',
        'Master', NULL),
       (UUID_TO_BIN(UUID()), '토심이 체크카드', 'KB국민카드', '버스·지하철 2~4천원 환급, 편의점·카페·영화·쇼핑·간편결제 2~4천원 환급', '30만원 이상', 'Master',
        NULL),
       (UUID_TO_BIN(UUID()), '카드의정석 오하CHECK', '우리카드', '온라인쇼핑·간편결제·커피 5% 캐시백, 안경·배달앱·대중교통·통신 5% 캐시백', '20만원 이상',
        'Master', NULL),
       (UUID_TO_BIN(UUID()), '직장인보너스체크카드', 'KB국민카드', '국세·지방세 7,000원 할인, GS칼텍스 50~60원/L 할인, 백화점 5% 할인', '20만원 이상',
        'VISA, Master', NULL),
       (UUID_TO_BIN(UUID()), '노리체크카드', 'KB국민카드', '대중교통 10% 청구할인, 이동통신요금 2,500원 환급, CGV 35% 환급, 푸드·테마파크 20~50% 할인',
        '20만원 이상', 'VISA, Master, UnionPay', NULL),
       (UUID_TO_BIN(UUID()), '신한카드 플리 체크 (산리오캐릭터즈)', '신한카드',
        '국내 0.3% 할인, 해외 0.2% 할인, 월 2회 할인쿠폰, My Pick 가맹점 월 3·6·9번째 이용 시 1,000포인트 적립', '없음', 'Master', NULL),
       (UUID_TO_BIN(UUID()), '가온 올포인트 체크카드', 'KB국민카드',
        '국내외 가맹점 0.2% 기본적립, 커피·통신·편의점·교통 0.2% 추가적립, 대형마트·GS칼텍스 0.8% 추가적립', '10만원 이상', 'Master', NULL);