UPDATE deposit_product SET profile = '느긋한 모험가' WHERE kor_co_nm = '경남은행' AND fin_prdt_nm = 'BNK 위더스자유적금';
UPDATE deposit_product SET profile = '자유로운 탐험가' WHERE kor_co_nm = '경남은행' AND fin_prdt_nm = 'BNK더조은자유적금';
UPDATE deposit_product SET profile = '자유로운 탐험가' WHERE kor_co_nm = '경남은행' AND fin_prdt_nm = 'BNK더조은정기예금';
UPDATE deposit_product SET profile = '현재를 즐기는 욜로족' WHERE kor_co_nm = '경남은행' AND fin_prdt_nm = 'The든든예금(시즌2)';
UPDATE deposit_product SET profile = '현실적인 계획가' WHERE kor_co_nm = '경남은행' AND fin_prdt_nm = 'The파트너예금';
UPDATE deposit_product SET profile = '현재를 즐기는 욜로족' WHERE kor_co_nm = '경남은행' AND fin_prdt_nm = '오늘도세이브적금';
UPDATE deposit_product SET profile = '현실적인 계획가' WHERE kor_co_nm = '경남은행' AND fin_prdt_nm = '주거래 프리미엄 적금';
UPDATE deposit_product SET profile = '현실적인 계획가' WHERE kor_co_nm = '경남은행' AND fin_prdt_nm = '행복 DREAM 적금';
UPDATE deposit_product SET profile = '실용적 준비자' WHERE kor_co_nm = '광주은행' AND fin_prdt_nm = 'The플러스예금';
UPDATE deposit_product SET profile = '비전 있는 자수성가형' WHERE kor_co_nm = '광주은행' AND fin_prdt_nm = 'VIP플러스적금';
UPDATE deposit_product SET profile = '스마트한 투자자' WHERE kor_co_nm = '광주은행' AND fin_prdt_nm = '굿스타트예금';
UPDATE deposit_product SET profile = '비전 있는 자수성가형' WHERE kor_co_nm = '광주은행' AND fin_prdt_nm = '미즈월복리정기예금';
UPDATE deposit_product SET profile = '현실적인 계획가' WHERE kor_co_nm = '광주은행' AND fin_prdt_nm = '스마트모아Dream정기예금';
UPDATE deposit_product SET profile = '느긋한 모험가' WHERE kor_co_nm = '광주은행' AND fin_prdt_nm = '여행스케치_남도투어적금';
UPDATE deposit_product SET profile = '자유로운 탐험가' WHERE kor_co_nm = '광주은행' AND fin_prdt_nm = '해피라이프_여행스케치적금V';
UPDATE deposit_product SET profile = '안정적인 관리자' WHERE kor_co_nm = '국민은행' AND fin_prdt_nm = 'KB Star 정기예금';
UPDATE deposit_product SET profile = '현재를 즐기는 욜로족' WHERE kor_co_nm = '국민은행' AND fin_prdt_nm = 'KB 특★한 적금';
UPDATE deposit_product SET profile = '안정적인 관리자' WHERE kor_co_nm = '국민은행' AND fin_prdt_nm = 'KB국민프리미엄적금(정액)';
UPDATE deposit_product SET profile = '자유로운 탐험가' WHERE kor_co_nm = '국민은행' AND fin_prdt_nm = 'KB내맘대로적금';
UPDATE deposit_product SET profile = '느긋한 모험가' WHERE kor_co_nm = '국민은행' AND fin_prdt_nm = 'KB맑은하늘적금';
UPDATE deposit_product SET profile = '현실적인 계획가' WHERE kor_co_nm = '농협은행주식회사' AND fin_prdt_nm = 'NH1934월복리적금';
UPDATE deposit_product SET profile = '느긋한 모험가' WHERE kor_co_nm = '농협은행주식회사' AND fin_prdt_nm = 'NH고향사랑기부예금';
UPDATE deposit_product SET profile = '느긋한 모험가' WHERE kor_co_nm = '농협은행주식회사' AND fin_prdt_nm = 'NH고향사랑기부적금';
UPDATE deposit_product SET profile = '느긋한 모험가' WHERE kor_co_nm = '농협은행주식회사' AND fin_prdt_nm = 'NH내가Green초록세상예금';
UPDATE deposit_product SET profile = '느긋한 모험가' WHERE kor_co_nm = '농협은행주식회사' AND fin_prdt_nm = 'NH내가Green초록세상적금';
UPDATE deposit_product SET profile = '현실적인 계획가' WHERE kor_co_nm = '농협은행주식회사' AND fin_prdt_nm = 'NH올원e 미니적금';
UPDATE deposit_product SET profile = '안정적인 관리자' WHERE kor_co_nm = '농협은행주식회사' AND fin_prdt_nm = 'NH올원e예금';
UPDATE deposit_product SET profile = '스마트한 투자자' WHERE kor_co_nm = '농협은행주식회사' AND fin_prdt_nm = 'NH왈츠회전예금 II';
UPDATE deposit_product SET profile = '현실적인 계획가' WHERE kor_co_nm = '농협은행주식회사' AND fin_prdt_nm = 'NH직장인월복리적금';
UPDATE deposit_product SET profile = '자유로운 탐험가' WHERE kor_co_nm = '부산은행' AND fin_prdt_nm LIKE 'BNK내맘대로%적금';
UPDATE deposit_product SET profile = '현재를 즐기는 욜로족' WHERE kor_co_nm = '부산은행' AND fin_prdt_nm = 'LIVE정기예금';
UPDATE deposit_product SET profile = '현실적인 계획가' WHERE kor_co_nm = '부산은행' AND fin_prdt_nm = 'Only One 주거래 우대적금';
UPDATE deposit_product SET profile = '스마트한 투자자' WHERE kor_co_nm = '부산은행' AND fin_prdt_nm = '더(The) 레벨업 정기예금';
UPDATE deposit_product SET profile = '현재를 즐기는 욜로족' WHERE kor_co_nm = '부산은행' AND fin_prdt_nm = '더(The) 특판 정기예금';
UPDATE deposit_product SET profile = '현재를 즐기는 욜로족' WHERE kor_co_nm = '부산은행' AND fin_prdt_nm LIKE '부산이라 좋다%Big적금';
UPDATE deposit_product SET profile = '느긋한 모험가' WHERE kor_co_nm = '부산은행' AND fin_prdt_nm = '저탄소 실천 적금';
UPDATE deposit_product SET profile = '비전 있는 자수성가형' WHERE kor_co_nm = '부산은행' AND fin_prdt_nm = '펫 적금';
UPDATE deposit_product SET profile = '스마트한 투자자' WHERE kor_co_nm = '수협은행' AND fin_prdt_nm = 'Sh월복리자유적금';
UPDATE deposit_product SET profile = '스마트한 투자자' WHERE kor_co_nm = '수협은행' AND fin_prdt_nm = 'Sh첫만남우대예금';
UPDATE deposit_product SET profile = '실용적 준비자' WHERE kor_co_nm = '수협은행' AND fin_prdt_nm LIKE 'Sh평생주거래우대예금%(만기일시지급식)';
UPDATE deposit_product SET profile = '느긋한 모험가' WHERE kor_co_nm = '수협은행' AND fin_prdt_nm LIKE 'Sh해양플라스틱Zero!예금%(만기일시지급식)';
UPDATE deposit_product SET profile = '느긋한 모험가' WHERE kor_co_nm = '수협은행' AND fin_prdt_nm LIKE 'Sh해양플라스틱Zero!적금%(정액적립식)';
UPDATE deposit_product SET profile = '느긋한 모험가' WHERE kor_co_nm = '수협은행' AND fin_prdt_nm LIKE 'Sh해양플라스틱Zero!적금%(자유적립식)';
UPDATE deposit_product SET profile = '안정적인 관리자' WHERE kor_co_nm = '수협은행' AND fin_prdt_nm = '헤이(Hey)정기예금';
UPDATE deposit_product SET profile = '현실적인 계획가' WHERE kor_co_nm = '신한은행' AND fin_prdt_nm = '신한 알.쏠 적금';
UPDATE deposit_product SET profile = '안정적인 관리자' WHERE kor_co_nm = '신한은행' AND fin_prdt_nm = '쏠편한 정기예금';
UPDATE deposit_product SET profile = '스마트한 투자자' WHERE kor_co_nm = '아이엠뱅크' AND fin_prdt_nm = 'iM스마트예금';
UPDATE deposit_product SET profile = '현실적인 계획가' WHERE kor_co_nm = '아이엠뱅크' AND fin_prdt_nm = 'iM스마트적금';
UPDATE deposit_product SET profile = '스마트한 투자자' WHERE kor_co_nm = '아이엠뱅크' AND fin_prdt_nm = 'iM주거래우대예금(첫만남고객형)';
UPDATE deposit_product SET profile = '스마트한 투자자' WHERE kor_co_nm = '아이엠뱅크' AND fin_prdt_nm = 'iM함께예금';
UPDATE deposit_product SET profile = '비전 있는 자수성가형' WHERE kor_co_nm = '아이엠뱅크' AND fin_prdt_nm = 'iM행복파트너예금(일반형)';
UPDATE deposit_product SET profile = '스마트한 투자자' WHERE kor_co_nm = '아이엠뱅크' AND fin_prdt_nm = '내가만든 보너스적금';
UPDATE deposit_product SET profile = '스마트한 투자자' WHERE kor_co_nm = '아이엠뱅크' AND fin_prdt_nm = '내손안에 적금';
UPDATE deposit_product SET profile = '비전 있는 자수성가형' WHERE kor_co_nm = '아이엠뱅크' AND fin_prdt_nm = '영플러스적금';
UPDATE deposit_product SET profile = '실용적 준비자' WHERE kor_co_nm = '우리은행' AND fin_prdt_nm = 'WON적금';
UPDATE deposit_product SET profile = '안정적인 관리자' WHERE kor_co_nm = '우리은행' AND fin_prdt_nm = 'WON플러스예금';
UPDATE deposit_product SET profile = '현실적인 계획가' WHERE kor_co_nm = '우리은행' AND fin_prdt_nm = '우리SUPER주거래적금';
UPDATE deposit_product SET profile = '비전 있는 자수성가형' WHERE kor_co_nm = '전북은행' AND fin_prdt_nm LIKE 'JB 123 정기예금%(만기일시지급식)';
UPDATE deposit_product SET profile = '안정적인 관리자' WHERE kor_co_nm = '전북은행' AND fin_prdt_nm LIKE 'JB 다이렉트예금통장%(만기일시지급식)';
UPDATE deposit_product SET profile = '자유로운 탐험가' WHERE kor_co_nm = '전북은행' AND fin_prdt_nm = 'JB 다이렉트적금(자유적립식)';
UPDATE deposit_product SET profile = '현실적인 계획가' WHERE kor_co_nm = '전북은행' AND fin_prdt_nm = 'JB 다이렉트적금(정액적립식)';
UPDATE deposit_product SET profile = '실용적 준비자' WHERE kor_co_nm = '전북은행' AND fin_prdt_nm = '내맘 쏙 정기예금';
UPDATE deposit_product SET profile = '스마트한 투자자' WHERE kor_co_nm = '제주은행' AND fin_prdt_nm = 'jbank 저금통적금';
UPDATE deposit_product SET profile = '스마트한 투자자' WHERE kor_co_nm = '제주은행' AND fin_prdt_nm LIKE 'J정기예금%(만기지급식)';
UPDATE deposit_product SET profile = '현실적인 계획가' WHERE kor_co_nm = '제주은행' AND fin_prdt_nm = 'MZ 플랜적금';
UPDATE deposit_product SET profile = '스마트한 투자자' WHERE kor_co_nm = '제주은행' AND fin_prdt_nm LIKE '스마일드림%정기예금%(개인/선이자%지급식)';
UPDATE deposit_product SET profile = '스마트한 투자자' WHERE kor_co_nm = '제주은행' AND fin_prdt_nm LIKE '제주Dream%정기예금%(개인/만기%지급식)';
UPDATE deposit_product SET profile = '스마트한 투자자' WHERE kor_co_nm = '제주은행' AND fin_prdt_nm = '탐이나요적금';
UPDATE deposit_product SET profile = '현재를 즐기는 욜로족' WHERE kor_co_nm = '주식회사 카카오뱅크' AND fin_prdt_nm = '카카오뱅크 26주적금';
UPDATE deposit_product SET profile = '현실적인 계획가' WHERE kor_co_nm = '주식회사 카카오뱅크' AND fin_prdt_nm = '카카오뱅크 자유적금';
UPDATE deposit_product SET profile = '안정적인 관리자' WHERE kor_co_nm = '주식회사 카카오뱅크' AND fin_prdt_nm = '카카오뱅크 정기예금';
UPDATE deposit_product SET profile = '현재를 즐기는 욜로족' WHERE kor_co_nm = '주식회사 카카오뱅크' AND fin_prdt_nm = '카카오뱅크 한달적금';
UPDATE deposit_product SET profile = '현재를 즐기는 욜로족' WHERE kor_co_nm = '주식회사 케이뱅크' AND fin_prdt_nm = '궁금한 적금';
UPDATE deposit_product SET profile = '현재를 즐기는 욜로족' WHERE kor_co_nm = '주식회사 케이뱅크' AND fin_prdt_nm = '데굴데굴 농장';
UPDATE deposit_product SET profile = '현실적인 계획가' WHERE kor_co_nm = '주식회사 케이뱅크' AND fin_prdt_nm = '주거래우대 자유적금';
UPDATE deposit_product SET profile = '자유로운 탐험가' WHERE kor_co_nm = '주식회사 케이뱅크' AND fin_prdt_nm = '코드K 자유적금';
UPDATE deposit_product SET profile = '안정적인 관리자' WHERE kor_co_nm = '주식회사 케이뱅크' AND fin_prdt_nm = '코드K 정기예금';
UPDATE deposit_product SET profile = '현실적인 계획가' WHERE kor_co_nm = '주식회사 하나은행' AND fin_prdt_nm = '내맘적금';
UPDATE deposit_product SET profile = '현실적인 계획가' WHERE kor_co_nm = '주식회사 하나은행' AND fin_prdt_nm = '주거래하나 월복리적금';
UPDATE deposit_product SET profile = '안정적인 관리자' WHERE kor_co_nm = '주식회사 하나은행' AND fin_prdt_nm = '하나의정기예금';
UPDATE deposit_product SET profile = '비전 있는 자수성가형' WHERE kor_co_nm = '중소기업은행' AND fin_prdt_nm = 'IBK D-day적금(자유적립식)';
UPDATE deposit_product SET profile = '안정적인 관리자' WHERE kor_co_nm = '중소기업은행' AND fin_prdt_nm = 'IBK굴리기통장(정기예금)';
UPDATE deposit_product SET profile = '안정적인 관리자' WHERE kor_co_nm = '중소기업은행' AND fin_prdt_nm = 'IBK더굴리기통장(실세금리정기예금)';
UPDATE deposit_product SET profile = '느긋한 모험가' WHERE kor_co_nm = '중소기업은행' AND fin_prdt_nm = 'IBK모으기통장(자유적립식)';
UPDATE deposit_product SET profile = '비전 있는 자수성가형' WHERE kor_co_nm = '중소기업은행' AND fin_prdt_nm LIKE 'IBK중기근로자우대적금%(자유적립식)';
UPDATE deposit_product SET profile = '느긋한 모험가' WHERE kor_co_nm = '중소기업은행' AND fin_prdt_nm = 'IBK탄소제로적금(자유적립식)';
UPDATE deposit_product SET profile = '현실적인 계획가' WHERE kor_co_nm = '중소기업은행' AND fin_prdt_nm = 'IBK평생한가족통장(실세금리정기예금)';
UPDATE deposit_product SET profile = '실용적 준비자' WHERE kor_co_nm = '토스뱅크 주식회사' AND fin_prdt_nm = '토스뱅크 굴비 적금';
UPDATE deposit_product SET profile = '안정적인 관리자' WHERE kor_co_nm = '토스뱅크 주식회사' AND fin_prdt_nm = '토스뱅크 먼저 이자 받는 정기예금';
UPDATE deposit_product SET profile = '실용적 준비자' WHERE kor_co_nm = '토스뱅크 주식회사' AND fin_prdt_nm = '토스뱅크 아이 적금';
UPDATE deposit_product SET profile = '자유로운 탐험가' WHERE kor_co_nm = '토스뱅크 주식회사' AND fin_prdt_nm = '토스뱅크 자유 적금';
UPDATE deposit_product SET profile = '실용적 준비자' WHERE kor_co_nm = '토스뱅크 주식회사' AND fin_prdt_nm = '토스뱅크 키워봐요 적금';
UPDATE deposit_product SET profile = '비전 있는 자수성가형' WHERE kor_co_nm = '한국산업은행' AND fin_prdt_nm = 'KDB 기업정기적금';
UPDATE deposit_product SET profile = '안정적인 관리자' WHERE kor_co_nm = '한국산업은행' AND fin_prdt_nm = 'KDB 자유적금';
UPDATE deposit_product SET profile = '안정적인 관리자' WHERE kor_co_nm = '한국산업은행' AND fin_prdt_nm = 'KDB 정기예금';
UPDATE deposit_product SET profile = '스마트한 투자자' WHERE kor_co_nm = '한국스탠다드차타드은행' AND fin_prdt_nm = 'e-그린세이브예금';
UPDATE deposit_product SET profile = '안정적인 관리자' WHERE kor_co_nm = '한국스탠다드차타드은행' AND fin_prdt_nm = '퍼스트가계적금';
